package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"ldaptest/auth"
	"ldaptest/graph/model"
	"strings"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	// Authenticate user against LDAP
	ldapUser, err := r.LDAPClient.AuthenticateUser(username, password)
	if err != nil {
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	// Generate JWT token
	token, err := auth.GenerateToken(ldapUser.UID, ldapUser.Email, ldapUser.FirstName, ldapUser.LastName, ldapUser.UserType)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	// Return auth payload
	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        ldapUser.UID,
			Username:  ldapUser.UID,
			Email:     ldapUser.Email,
			FirstName: ldapUser.FirstName,
			LastName:  ldapUser.LastName,
			UserType:  ldapUser.UserType,
		},
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string, email string, firstName string, lastName string, userType string) (*model.AuthPayload, error) {
	// Validate userType
	if userType != "internal" && userType != "external" {
		userType = "external" // Default to external
	}

	// Create user in LDAP
	ldapUser, err := r.LDAPClient.CreateUser(username, password, email, firstName, lastName, userType)
	if err != nil {
		if strings.Contains(err.Error(), "already exists") {
			return nil, fmt.Errorf("username already exists")
		}
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Generate JWT token
	token, err := auth.GenerateToken(ldapUser.UID, ldapUser.Email, ldapUser.FirstName, ldapUser.LastName, ldapUser.UserType)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	// Return auth payload
	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        ldapUser.UID,
			Username:  ldapUser.UID,
			Email:     ldapUser.Email,
			FirstName: ldapUser.FirstName,
			LastName:  ldapUser.LastName,
			UserType:  ldapUser.UserType,
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Get user from context
	user := auth.ForContext(ctx)
	if user == nil {
		return nil, fmt.Errorf("unauthorized: no user in context")
	}

	return &model.User{
		ID:        user.Username,
		Username:  user.Username,
		Email:     user.Email,
		FirstName: user.FirstName,
		LastName:  user.LastName,
		UserType:  user.UserType,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	// Require authentication
	currentUser := auth.ForContext(ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized")
	}

	// Get user from LDAP
	ldapUser, err := r.LDAPClient.GetUserByUID(username)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	return &model.User{
		ID:        ldapUser.UID,
		Username:  ldapUser.UID,
		Email:     ldapUser.Email,
		FirstName: ldapUser.FirstName,
		LastName:  ldapUser.LastName,
		UserType:  ldapUser.UserType,
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "GraphQL LDAP server is healthy!", nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
